services:
  etcd:
    image: bitnamilegacy/etcd:3.5.11
    container_name: f-cloud-etcd
    restart: always
    network_mode: "host"
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://127.0.0.1:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"

  consul:
    image: hashicorp/consul:1.21.3
    container_name: f-cloud-consul
    restart: always
    network_mode: "host"
    command: "agent -dev -config-dir=/etc/consul.d/"
    volumes:
      - ./consul_conf:/etc/consul.d/

  apisix:
    container_name: f-cloud-apisix
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.14.1-debian}
    network_mode: "host"
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
      - consul
  
  jaeger:
    image: jaegertracing/jaeger:2.11.0
    container_name: f-cloud-jaeger
    restart: always
    network_mode: "host"

  redis:
    image: redis:7.4.6
    container_name: f-cloud-redis
    restart: always
    network_mode: "host"